# Generated by Django 3.1.7 on 2021-04-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0003_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='streamers.streamer'),
        ),
    ]
