# Generated by Django 3.1.7 on 2021-04-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0004_auto_20210424_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='tag_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
