# Generated by Django 3.1.7 on 2021-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0005_auto_20210424_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterField(
            model_name='streamer',
            name='twitch_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='twitch_username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
