# Generated by Django 3.1.7 on 2021-10-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0006_auto_20210425_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='subscription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
