# Generated by Django 3.1.7 on 2021-10-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0007_streamer_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='subscription',
            new_name='online_subscription',
        ),
    ]
