# Generated by Django 3.1.7 on 2021-10-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0008_auto_20211025_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='offline_subscription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
