version: '3'

services:
  app:
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      REDIS_ENDPOINT: ${REDIS_ENDPOINT:-redis:6379}
      DJANGO_DB_TYPE: ${DJANGO_DB_TYPE:-postgres}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST:-db}
      DJANGO_DB: ${DJANGO_DB:-tau_db}
      DJANGO_DB_USER: ${DJANGO_DB_USER:-tau_db}
      DJANGO_DB_PW: ${DJANGO_DB_PW}
      DJANGO_CONFIGURATION: ${DJANGO_CONFIGURATION:-Local}
      PROTOCOL: ${PROTOCOL:-http:}
      PUBLIC_URL: ${PUBLIC_URL:-localhost}
      USE_NGROK: ${USE_NGROK:-True}
      PORT: ${PORT:-8000}
      TWITCH_WEBHOOK_SECRET: ${TWITCH_WEBHOOK_SECRET}
    depends_on:
      - db
      - redis
    build:
      context: .
    volumes:
      - ./:/code:cached
    ports:
      - ${PORT:-8000}:${PORT:-8000}

    command: >
      bash -c "source ./scripts/loadenv.sh 
      && ./tau/config/validate.py
      && ./manage.py migrate
      && ./manage.py collectstatic --noinput
      && /usr/bin/supervisord -n -c /etc/supervisord.conf"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
  
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      DJANGO_DB: ${DJANGO_DB:-tau_db}
      DJANGO_DB_USER: ${DJANGO_DB_USER:-tau_db}
      DJANGO_DB_PW: ${DJANGO_DB_PW}

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  postgres-data:
