version: "3"

services:
  app:
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_CONNECTION: "postgres://postgres:${POSTGRES_PW}@db/tau_db"
      PORT: "${PORT:-8000}"
      TWITCH_WEBHOOK_SECRET: "${TWITCH_WEBHOOK_SECRET}"
    external_links:
      - "db:db"
    depends_on:
      - db
    build:
      context: .
    ports:
      - ${PORT:-8000}:${PORT:-8000}

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}

volumes:
  postgres-data:
