# Generated by Django 3.1.6 on 2021-02-14 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(max_length=255)),
                ('event_source', models.CharField(choices=[('PubSub', 'PubSub'), ('EventSub', 'EventSub')], max_length=32)),
                ('event_data', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
