# Generated by Django 3.1.7 on 2022-02-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchevents', '0004_auto_20211029_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchevent',
            name='event_source',
            field=models.CharField(choices=[('PubSub', 'PubSub'), ('EventSub', 'EventSub'), ('Test', 'Test')], max_length=32),
        ),
    ]
