# Generated by Django 3.1.7 on 2022-05-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_auto_20220514_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
