# Generated by Django 3.1.7 on 2022-05-25 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_auto_20220518_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=255)),
                ('chat_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='chatbots.chatbot')),
            ],
        ),
    ]
