# Generated by Django 3.1.7 on 2021-07-10 17:18

from django.db import migrations
from constance import config

def toggle_scope_update_required(apps, schema_editor):
    config.SCOPE_UPDATED_NEEDED = True

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(toggle_scope_update_required)
    ]
