# Generated by Django 3.1.7 on 2021-11-06 12:18

from django.db import migrations
from constance import config

def toggle_reset_webhooks(apps, schema_editor):
    config.RESET_ALL_WEBHOOKS = True

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_scope_update_for_chat'),
    ]

    operations = [
        migrations.RunPython(toggle_reset_webhooks)
    ]
