# Generated by Django 3.1.7 on 2021-06-09 00:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchAPIScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchHelixEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=16)),
                ('reference_url', models.CharField(max_length=255)),
                ('token_type', models.CharField(choices=[('OA', 'OAuth User Token'), ('AP', 'App Access Token')], max_length=2)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='twitch.twitchapiscope')),
            ],
        ),
    ]
