# Generated by Django 3.1.7 on 2021-06-09 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchapiscope',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='twitchhelixendpoint',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='twitch.twitchapiscope'),
        ),
    ]
