# Generated by Django 3.1.7 on 2021-06-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0002_auto_20210609_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twitchapiscope',
            options={'ordering': ['scope']},
        ),
    ]
