# Generated by Django 3.1.7 on 2021-07-14 00:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0003_auto_20210618_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchEventSubSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subscription_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=16)),
                ('scope_required', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('DIS', 'Disconnected'), ('CTG', 'Connecting'), ('CON', 'Connected')], max_length=3, null=True)),
                ('base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription', models.JSONField(blank=True, null=True)),
                ('event_type', models.JSONField()),
            ],
        ),
    ]
