# Generated by Django 3.1.7 on 2021-07-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0005_twitcheventsubsubscription_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitcheventsubsubscription',
            old_name='event_type',
            new_name='event_schema',
        ),
    ]
