# Generated by Django 3.1.7 on 2021-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0007_auto_20210715_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitcheventsubsubscription',
            name='scope_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
