# Generated by Django 3.1.7 on 2021-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0010_auto_20210722_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitcheventsubsubscription',
            name='lookup_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='twitcheventsubsubscription',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
