# Generated by Django 3.1.7 on 2022-03-02 19:57

from django.db import migrations


def update_eventsub_subscription_data(apps, schema_editor):
    TwitchEventSubSubscription = apps.get_model('twitch', 'TwitchEventSubSubscription')
    for event_sub in TwitchEventSubSubscription.objects.all():
        sub_data = event_sub.subscription
        if (sub_data is not None) and (not isinstance(sub_data, list)):
            event_sub.subscription = [sub_data]
            event_sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0011_auto_20210722_2040'),
    ]

    operations = [
        migrations.RunPython(update_eventsub_subscription_data),
    ]
